<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="UTF-8" />
		<meta name="viewport" content="width=device-width, initial-scale=1.0" />
		<title>COS10026 Project Part 1</title>
		<link rel="stylesheet" href="./styles/styles.css" />
		<style>
			@import url('https://fonts.googleapis.com/css2?family=Koulen&family=Montserrat:ital,wght@0,100..900;1,100..900&display=swap');
		</style>
	</head>
	<body>
		<p>THIS IS THE IMPORT</p>
	</body>
</html>
