<nav class="original">
      <a href="index.php" class="home">Bitbops </a>
      <div class="navbar">
        <a href="about.php" class="about">About</a>
        <a href="jobs.php" class="jobs">Jobs</a>
        <a href="apply.php" class="apply">Applications</a>
        <a href="enhancements.php" class="enhancements">Enhancements</a>
        <a href="mailto:" class="email">Contact</a>
      </div>
    </nav>

    <header>
      <nav>
        <input type="checkbox" id="check" />
        <label for="check" class="open-menu">&#9776;</label>
        <a href="index.php" class="home">BITBOPS</a>
        <ul class="menu">
          <li><a href="about.php">About</a></li>
          <li><a href="jobs.php">Jobs</a></li>
          <li><a href="apply.html">Apply</a></li>
          <li><a href="enhancements.php">Enhancements</a></li>
          <li><a href="mailto:105728093@swin.edu.au">Contact</a></li>
        </ul>
        <label for="check" class="close-menu">&#9747;</label>
      </nav>
    </header>
